require 'kaminari/neo4j/version'
require 'active_support'
require 'neo4j'
require 'kaminari'
require 'kaminari/models/configuration_methods'
require 'kaminari/neo4j/criteria_methods'
require 'kaminari/neo4j/paginated'
require 'kaminari/neo4j/extension'
require 'kaminari/neo4j/hooks'
Kaminari::Neo4j::Hooks.init
